export const ContactInitialState = {
  id: 0,
  first_name: "",
  last_name: "",
  first_email: "",
  second_email: "",
  first_phone: "",
  second_phone: "",
  third_phone: "",
  first_cep: 0,
  first_address: "",
  first_neighbourhood: "",
  first_city: "",
  first_uf: "",
  first_number: 0,
  second_cep: 0,
  second_address: "",
  second_neighbourhood: "",
  second_city: "",
  second_uf: "",
  second_number: 0,
  notes: "",
  fixed: false,
};
